CREATE TABLE User (
	UserID INT AUTO_INCREMENT PRIMARY KEY,
	Username VARCHAR(100) NOT NULL UNIQUE,
	Email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Note (
	NoteID INT AUTO_INCREMENT PRIMARY KEY,
	Title VARCHAR(100) NOT NULL,
	Content TEXT,
	CategoryID INT,
	UserID INT,
	FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID),
	FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Media (
	MediaID INT AUTO_INCREMENT PRIMARY KEY,
	MediaType ENUM('Image', 'Video', 'Other') NOT NULL,
	MediaURL VARCHAR(255) NOT NULL,
	NoteID INT,
	FOREIGN KEY (NoteID) REFERENCES Note(NoteID)
);

CREATE TABLE Task (
	TaskID INT AUTO_INCREMENT PRIMARY KEY,
	Title VARCHAR(100) NOT NULL,
	Description TEXT,
	Status ENUM('Pending', 'In Progress', 'Completed') NOT NULL,
	UserID INT,
	FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Page (
	PageID INT AUTO_INCREMENT PRIMARY KEY,
	Title VARCHAR(100) NOT NULL,
	Content TEXT,
	UserID INT,
	FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE Category (
	CategoryID INT AUTO_INCREMENT PRIMARY KEY,
	CategoryName VARCHAR(50) NOT NULL
);
